run : 第17-24回\ 计算机科学与技术系\ 171860624\ 毕秋宇.tex preamble.tex
	xelatex -shell-escape -synctex=1 -interaction=nonstopmode 第17-24回\ 计算机科学与技术系\ 171860624\ 毕秋宇.tex
	open 第17-24回\ 计算机科学与技术系\ 171860624\ 毕秋宇.pdf
	notifyloop 第17-24回\ 计算机科学与技术系\ 171860624\ 毕秋宇.tex make lop

lop : 第17-24回\ 计算机科学与技术系\ 171860624\ 毕秋宇.tex preamble.tex
	xelatex -shell-escape -synctex=1 -interaction=nonstopmode 第17-24回\ 计算机科学与技术系\ 171860624\ 毕秋宇.tex

clean :
	rm -r *.bib *.blg *.bbl *.aux *.log *.brf *.nlo *.out *.dvi *.ps *.lof *.toc *.fls *.fdb_latexmk *.pdfsync *.synctex*.gz *.ind *.ilg *.idx
